export default {
  // common
  LOADING_START: 'LOADING_START',
  LOADING_END: 'LOADING_END',
  COMMON_FAILURE: 'COMMON_FAILURE',

  SMSCODE_SEND_REQUEST: 'SMSCODE_SEND_REQUEST',
  SMSCODE_SEND_SUCCESS: 'SMSCODE_SEND_SUCCESS',
  SMSCODE_SEND_FAILURE: 'SMSCODE_SEND_FAILURE',
  // 组合请求
  COMMON_FETCH_REQUEST: 'COMMON_FETCH_REQUEST',
  COMMON_FETCH_SUCCESS: 'COMMON_FETCH_SUCCESS',
  COMMON_FETCH_FAILURE: 'COMMON_FETCH_FAILURE',
  // 字典
  DICT_FETCH_REQUEST: 'DICT_FETCH_REQUEST',
  DICT_FETCH_SUCCESS: 'DICT_FETCH_SUCCESS',
  DICT_FETCH_FAILURE: 'DICT_FETCH_FAILURE',
  // 城市
  AREA_FETCH_REQUEST: 'AREA_FETCH_REQUEST',
  AREA_FETCH_SUCCESS: 'AREA_FETCH_SUCCESS',
  AREA_FETCH_FAILURE: 'AREA_FETCH_FAILURE',
  // auth
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

  //city
  ALL_CITIES_FETCH_REQUEST: 'ALL_CITIES_FETCH_REQUEST',
  ALL_CITIES_FETCH_SUCCESS: 'ALL_CITIES_FETCH_SUCCESS',

  //home
  HOME_DATA_FETCH_REQUEST: 'HOME_DATA_FETCH_REQUEST',
  HOME_DATA_FETCH_SUCCESS: 'HOME_DATA_FETCH_SUCCESS',
}